version: "3.3"
services:
  expressapp:
    container_name: api-intranet
    build: ./api
    expose:
      - 3001
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1324
      - DB_DATABASE=Demo-Intranet
      - DB_HOST=db
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    networks:
      - intranet-network
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1324
      - POSTGRES_DB=Demo-Intranet
    networks:
      - intranet-network
  reactapp:
    container_name: client-intranet
    build: ./client
    expose:
      - 3000
    volumes:
      - ./client:/usr/src/app
    networks:
      - intranet-network
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - expressapp
      - reactapp
    restart: always
    networks:
      - intranet-network

networks:
  intranet-network:
    driver: bridge
