version: "3.3"
services:
  expressapp:
    container_name: expressapp
    build: ./api
    expose:
      - 3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1324
      - DB_DATABASE=Demo-Intranet
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1324
      - POSTGRES_DB=Demo-Intranet
  reactapp:
    container_name: reactapp
    build: ./client
    expose:
      - 3000
    volumes:
      - ./client:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - expressapp
      - reactapp
    restart: always
